version: "3.3"
services:
  db:
    image: mysql:8.0.13
    environment:
      - MYSQL_ROOT_PASSWORD=magicy
      - MYSQL_DATABASE=magicy
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
      - TZ=Europe/Warsaw
    ports:
      - 4222:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
  app:
    build:
      context: ./
    image: jjdz5-magicy_app
    container_name: jjdz5magicy-app
    ports:
      - 4220:8080
      - 4221:9990
    depends_on:
      - db
    links:
      - db
    dns: 8.8.8.8