package com.infoshareacademy.usersengine.services;

public enum Property {

    API_KEY,

    REDIRECTION_DELAY,

    ADVERT_MAX_PERIOD_DAYS,
    ADVERT_MIN_HOURS_TO_START,

    MSG_ADVERT_ADD_OK,
    MSG_BAD_MAIN_START_ADDRESS,
    MSG_BAD_MAIN_END_ADDRESS,
    MSG_BAD_DETAIL_START_ADDRESS,
    MSG_BAD_DETAIL_END_ADDRESS,
    MSG_EQUAL_ADDRESSES,
    MSG_BAD_START_TIME,
    MSG_BAD_END_TIME,
    MSG_EARLY_START_TIME,
    MSG_START_AFTER_END_TIME,
    MSG_BAD_DATE,
    MSG_BAD_DRIVER,
    MSG_BAD_CAR


}
