<#--<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>-->
<script src="https://apis.google.com/js/platform.js" async defer></script>
<script src="https://apis.google.com/js/client.js" async defer></script>
<meta name="google-signin-scope" content="profile email">
<meta name="google-signin-client_id" content="714386444263-rduec7llk6q3odjpqf6ong5tp4kqb4n1.apps.googleusercontent.com">
<#--<meta name="google-signin-client_id" content="444424982972-jklpm47ig2ven5u2crll8kha0o1g37dj.apps.googleusercontent.com">-->
