<!doctype html>
<html lang="pl">
<head>
    <meta charset="UTF-8"/>
    <title>goTogether</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"/>
</head>

<body>



<nav class="navbar navbar-expand-lg navbar-light bg-light shadow p-3 mb-5  rounded" style="align-content: center">
    <a class="navbar-brand" href="#">goTogether</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-center" id="navbarNav">
        <div class="btn-group btn-group-toggle" data-toggle="buttons">
            <label class="btn btn-secondary">
                <input type="radio" name="options" id="option1" autocomplete="off"> Show adverts
            </label>
            <label class="btn btn-secondary">
                <input type="radio" name="options" id="option2" autocomplete="off"> Add advert
            </label>
            <label class="btn btn-secondary">
                <input type="radio" name="options" id="option3" autocomplete="off"> Filter adverts
            </label>
            <label class="btn btn-secondary">
                <input type="radio" name="options" id="option4" autocomplete="off"> Driver's rating
            </label>
        </div>
    </div>
</nav>










<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>

<script src="scripts.js"></script>
</body>
</html>